--COMANDO PARA A CRIA플O DE UM NOVO BANCO DE DADOS
CREATE DATABASE ESCOLA;

--COLOCAR BANCO DE DADOS EM USO
USE ESCOLA;

--CRIA플O DE TABELA NO BANCO DE DADOS
CREATE TABLE ALUNOS
(
	CODIGO INT,
	NOME CHAR(30),
	IDADE INT,
	EMAIL CHAR(50),
	FONE_RES CHAR(10),
	FONE_CEL CHAR(11),
	PROFISSAO CHAR(20)

);

--INSERIR DADOS NA TABELA ALUNOS
INSERT INTO ALUNOS (CODIGO, NOME, IDADE, EMAIL, FONE_RES, FONE_CEL, PROFISSAO) 
VALUES (1, 'JULIO',25, 'JULIO@ESCOLA.COM','413333333','4199999999','DESENVOLVEDOR');

INSERT INTO ALUNOS (CODIGO, NOME, IDADE, EMAIL, FONE_RES, FONE_CEL, PROFISSAO) 
VALUES (1, 'LUCIANE',38, 'LUCIANE@ESCOLA.COM','413333333','4199999999','ANALISTA');


--SELECIONAR E VISUALIZAR OS DADOS DA TAELA ALUNOS
SELECT * FROM ALUNOS

--EXCLUIR A TABELA ALUNOS
DROP TABLE ALUNOS;

--CRIA플O DE TABELA NO BANCO DE DADOS CHAVE PRIMARIA
CREATE TABLE ALUNOS
(
	CODIGO INT PRIMARY KEY ,
	NOME CHAR(30),
	IDADE INT,
	EMAIL CHAR(50),
	FONE_RES CHAR(10),
	FONE_CEL CHAR(11),
	PROFISSAO CHAR(20)

);

--INSERIR DADOS NA TABELA ALUNO
INSERT INTO ALUNOS (CODIGO, NOME, IDADE, EMAIL, FONE_RES, FONE_CEL, PROFISSAO) 
VALUES (1, 'JULIO',25, 'JULIO@ESCOLA.COM','413333333','4199999999','DESENVOLVEDOR');

--INSERCAO DE ALUNO COM CODIGO IGUAL PARA CAUSAR ERRO NA RESTRI플O DA PRIMARY KEY
INSERT INTO ALUNOS (CODIGO, NOME, IDADE, EMAIL, FONE_RES, FONE_CEL, PROFISSAO) 
VALUES (1, 'LUCIANE',38, 'LUCIANE@ESCOLA.COM','413333333','4199999999','ANALISTA');

--INSER플O ALTERANDO O CODIGO
INSERT INTO ALUNOS (CODIGO, NOME, IDADE, EMAIL, FONE_RES, FONE_CEL, PROFISSAO) 
VALUES (2, 'LUCIANE',38, 'LUCIANE@ESCOLA.COM','413333333','4199999999','ANALISTA');

--DROPAR A TABELA E CRIAR NOVAMENTE COM A SEGUINTE CONFIGURA플O
CREATE TABLE ALUNOS
(
	CODIGO INT PRIMARY KEY IDENTITY, --IDENTITY INSERE VALORES INCREMENTAIS NO CAMPO
	NOME CHAR(30),
	IDADE INT,
	EMAIL CHAR(50),
	FONE_RES CHAR(10),
	FONE_CEL CHAR(11),
	PROFISSAO CHAR(20)

);

INSERT INTO ALUNOS (NOME, IDADE, EMAIL, FONE_RES, FONE_CEL, PROFISSAO) 
VALUES ('JULIO',25, 'JULIO@ESCOLA.COM','413333333','4199999999','DESENVOLVEDOR');

--INSERCAO DE ALUNO COM CODIGO IGUAL PARA CAUSAR ERRO NA RESTRI플O DA PRIMARY KEY
INSERT INTO ALUNOS (NOME, IDADE, EMAIL, FONE_RES, FONE_CEL, PROFISSAO) 
VALUES ('LUCIANE',38, 'LUCIANE@ESCOLA.COM','413333333','4199999999','ANALISTA');

--INSERT DECLARATIVO
--INSERT INTO NOMEDATABELA (CAMPOS QUE DEVEM SER INSERIDOS) VALUES (VALORES NA ORDEM QUE DEFINIMOS NO PAENTESES ANTERIOR)

--INSERT POSICIONAL
--INSERT INTO NOMEDATABELA VALUES (VALORES NA ORDEM QUE OS CAMPOS FORAM CRIADOS)
INSERT INTO ALUNOS VALUES ('LUIZ',38,'LUIZ.LAZANO@SP,SENAI,BR','1111111111','11111111111','PROFESSOR');


INSERT ALUNOS (NOME,IDADE)
VALUES
('GUSTAVO', 24),
('THAIS', 24),
('LUIZ FERNANDO', 17)

--COMAND SELECT
USE PEDIDOS
SELECT